### ISSUE TITLE
dark theme support + message notification problem

### ISSUE THREAD

**Issue by Subroutine7901** [AgeOfMarcus/repl-dm-chrome#1]
![image](https://user-images.githubusercontent.com/77363873/109230418-182d2e00-7782-11eb-8aa6-9dacbffbd9bf.png)
when in dark theme you can barely see the text,
![image](https://user-images.githubusercontent.com/77363873/109230789-b02b1780-7782-11eb-9d66-a331c9b8228e.png)
and i choose dark theme for a reason, so please add dark theme support, and you can see there's no new messages when it says there is, please fix these
repl.it username: williham

**Comment by Subroutine7901** [comment]
and yes, this is the first issue in this repo

**Comment by AgeOfMarcus** [comment]
the dark theme bug should now be fixed, and we are working on fixing that bug with the number of unread messages

**Comment by Subroutine7901** [comment]
thanks
