### ISSUE TITLE
Domain change fix?

### ISSUE THREAD

**Issue by firefish111** [AgeOfMarcus/repl-dm-chrome#11]
Because repl.it has now changed to replit.com, should you update the extension? I know everybody could just manually é their way into the code, and fix it, but why can't we just release an update?

**Comment by 19wintersp** [comment]
It has already been fixed. You need to update your install.

**Comment by 19wintersp** [comment]
See #8

**Comment by 19wintersp** [comment]
#12 was merged, can this be closed?

**Comment by firefish111** [comment]
@19wintersp yes
