### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by whippingdot** [AgeOfMarcus/repl-dm-chrome#17]
Series problem with the icon. Check out the repo https://github.com/Repl-it-Coders/Repl-Favicon. Our favicon luks loike ur icon so...either you can join our org (with 26 peeps) or you can change ur icon. You don't have to change ur icon but it is similar...@Tsunami-Or-Something get a ping

**Comment by 19wintersp** [comment]
Both of them are just modifications of the Replit logo, and yours actually contains it, so I wouldn't go around trying to do this if I were you. Dupl also seems to be older than Repl.it Coders.

**Comment by whippingdot** [comment]
😮 lul k deleting it. I created this issue for fun...but ur right
