### ISSUE TITLE
Does Not Work

### ISSUE THREAD

**Issue by IronCodem** [AgeOfMarcus/repl-dm-chrome#18]
When I get the extension, this is what shows up: 
![image](https://user-images.githubusercontent.com/79524299/111783455-a03db980-8890-11eb-957d-e343a61d570d.png)

What do I do?

**Comment by AgeOfMarcus** [comment]
That's normal, we don't have a popup menu page yet, just open replit as
usual and it'll add the DM button to the left hand menu

**Comment by IronCodem** [comment]
Oh, all right then! Thanks!
