### ISSUE TITLE
add README

### ISSUE THREAD

**Issue by techpixel** [AgeOfMarcus/repl-dm-chrome#2]

**Comment by Subroutine7901** [comment]
well, the post on repl.it is good,
https://repl.it/talk/share/repldm-alpha-001-direct-messaging-in-replit/124217

**Comment by techpixel** [comment]
Take the post and turn it into a readme? Maybe deeper explanation.

**Comment by Subroutine7901** [comment]
idk
________________________________

**Comment by Subroutine7901** [comment]
yes, and i made a pull request to do just that

**Comment by techpixel** [comment]
I would have also expected some more documentation but this looks nice. #3

**Comment by AgeOfMarcus** [comment]
readme will be added
