### ISSUE TITLE
Authorization Error

### ISSUE THREAD

**Issue by jsavari** [AgeOfMarcus/repl-dm-chrome#23]
When I click the "Authorize" button on the extension, it opens a window and it shows I am logged in replit, but the authorization message appears again and this process repeats again. 
![error](https://user-images.githubusercontent.com/75747985/112994598-68f4c580-9138-11eb-9d2e-c2964bc4acc9.jpg)
![error1](https://user-images.githubusercontent.com/75747985/112994595-685c2f00-9138-11eb-8a70-88f52010cc4b.jpg)

**Comment by jsavari** [comment]
On the second picture, when clicking authorize it opens another window displaying the same.

**Comment by 19wintersp** [comment]
When you see the "Please login with your repl account" dialogue in the Repl Auth window, just close it by pressing the "X", and then press the light-blue "Authorize" button.

**Comment by jsavari** [comment]
Thanks!
