### ISSUE TITLE
Not an Issue a Question

### ISSUE THREAD

**Issue by rayhanadev** [AgeOfMarcus/repl-dm-chrome#25]
Hiya, I'm trying to make my own Chrome extension for Replit and I was curious as to how you made the sidebar button persist. Nextjs is awfully weird about how it loads content so my button only loads when the page is refreshed but it seems yours will load whenever we navigate through Replit. Just wondering how :)

**Comment by 19wintersp** [comment]
It [uses](https://github.com/AgeOfMarcus/repl-dm-chrome/blob/4c01ff70e328125f0772b1b327ee739da15fa8c3/foreground.js#L621) the "DOMSubtreeModified" event (see [Mutation events](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Mutation_events)) (which it *maybe* shouldn't) to detect changes in the page, and then calls the `setup` function after a timeout.

**Comment by 19wintersp** [comment]
If you want a non-deprecated alternative, look into [mutation observers](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver). Alternatively, you can check for non-reloading page changes (which use the [History API](https://developer.mozilla.org/en-US/docs/Web/API/History)) by either proxying `pushState` or by polling `location` for changes on an interval.

**Comment by rayhanadev** [comment]
Hmm, I saw and got it running! Is it a major problem using the deprecated feature?

**Comment by 19wintersp** [comment]
It's not a massive issue, but one would generally try to use standardised features. MDN says:

> ### Deprecated
> This feature is no longer recommended... Avoid using it, and update existing code if possible... this feature may cease to work at any time.

and also

> deprecated features can still be used, but should be used with caution because they are expected to be removed entirely sometime in the future. You should work to remove their use from your code.

**Comment by rayhanadev** [comment]
Okay gotcha, thanks!
