### ISSUE TITLE
Streamline authentication

### ISSUE THREAD

**Issue by 19wintersp** [AgeOfMarcus/repl-dm-chrome#6]
The current authentication system forces you to either open the authentication site in a new window, or use a frame in the authentication popup. It should be possible to only require the Repl Auth window, then have an API on the server which gives the authentication code to the JavaScript code automatically.

**Comment by AgeOfMarcus** [comment]
The repl Auth can't be used in the extension since the domain is different
to repl.it

**Comment by 19wintersp** [comment]
What do you mean? I meant was for you to open "auth_with_repl_site?domain=repldm.dupl.repl.co" as a popup, or if that's not possible, open the auth page in a hidden frame and make it automatically open the Repl Auth window, and then request to an API on "repldm.dupl.repl.co" to get the code.

**Comment by AgeOfMarcus** [comment]
I tried this initially, the problem is repl Auth can't then post a message
to the parent because the domain that opened it is repl.it due to how the
plugin works. I can't do the hidden iframe because I'm sure that would go
against repl.it or Google ToS.

**Comment by 19wintersp** [comment]
Could you try to poll "repldm.dupl" instead, and have the server respond if the authentication was successful?

**Comment by AgeOfMarcus** [comment]
What do you mean? Authentication must be done through repl.it to verify users

**Comment by 19wintersp** [comment]
Sorry for my late response; here's what I mean. To authenticate, "foreground.js" would do these steps:

1. Open "https://repl.it/auth_with_repl_site?domain=repldm.dupl.repl.co"; the user starts to authenticate
2. Immediately start polling an endpoint on "repldm.dupl.repl.co", let's call that "/is_authed"
    The ReplDM server receives the "/is_authed" request, and checks for "X-Replit-User-Name" headers. If they do not exist, the server returns an error code. If they do, the server will respond with 200 and the authentication code.
    "foreground.js" keeps requesting "/is_authed" until it receives 200. This means that we will be notified as soon as Replit has finished auth-ing.
3. Now that we have the authentication code, the Repl Auth window is closed, and authentication is complete.

**Comment by AgeOfMarcus** [comment]
Originally I tried that but it didn't work for some reason

**Comment by 19wintersp** [comment]
Okay then, I think the current system will just have to do; closing.
